---
- hosts: Spacewalk
  tasks:
    - name: Add Hostname
      shell: hostnamectl set-hostname test-spacewalk

    - name: Get Enforce
      command: getenforce
      register: result

    - name: Disabling selinux permanently
      shell: sed -i "s/SELINUX=enforcing/SELINUX=disabled/g" /etc/selinux/config
      when: result.stdout == "Enforcing"
      ignore_errors: True
      
    - name: Add repos 1
      shell: rpm -Uvh https://copr-be.cloud.fedoraproject.org/results/@spacewalkproject/spacewalk-2.9-client/epel-7-x86_64/00830558-spacewalk-repo/spacewalk-client-repo-2.9-4.el7.noarch.rpm  
      ignore_errors: True
      
    - name: Install Package
      yum: name=epel-release,rhn-client-tools,rhn-check,rhn-setup,rhnsd,m2crypto,yum-rhn-plugin,rhncfg-actions state=latest

    - name: Add repos Spacewalk Server
      shell: rpm -Uvh http://172.24.188.171/pub/rhn-org-trusted-ssl-cert-1.0-1.noarch.rpm
      ignore_errors: True

    - name: Stop Firewalld
      shell: systemctl stop firewalld

    - name: Registrar
      shell: rhnreg_ks --activationkey 1-754bd8f0fb0ba2d2ec6079fdfa9991cb --serverUrl https://172.24.188.171/XMLRPC

    - name: Forzar check
      shell: rhn_check

    - name: Activar actions
      shell: rhn-actions-control --enable-all

    - name: Forzar actions
      shell: rhn-profile-sync -vvvv
